services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: rtr_db
      POSTGRES_USER: road_to_russia
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db


  app:
    build: .
    environment:
      DB_URL: postgresql+asyncpg://road_to_russia:1234@db:5432/rtr_db
      DB_SYNC: postgres://road_to_russia:1234@db:5432/rtr_db
      TOKEN: ${TOKEN}       
    depends_on:
      - db
    volumes:                 
      - ./user_data.xlsx:/app/user_data.xlsx
      - ./mero.xlsx:/app/mero.xlsx

  alembic:
    extends: app
    command: alembic upgrade head
    depends_on:
      - db

  bot:
    extends: app
    command: python main.py
    depends_on:
      - alembic

  excel_import:
    extends: app
    command: python import_all.py   
    depends_on:
      - alembic


volumes:
  postgres_data:
