"""add meet model

Revision ID: 0bd70b2bd8a3
Revises: 56e5741b92d0
Create Date: 2025-06-06 16:01:31.125226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd70b2bd8a3'
down_revision: Union[str, None] = '56e5741b92d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('foreigner_tg_name', sa.String(), nullable=False),
    sa.Column('q1', sa.Text(), nullable=True),
    sa.Column('q2', sa.Text(), nullable=True),
    sa.Column('q3', sa.Text(), nullable=True),
    sa.Column('q4', sa.Text(), nullable=True),
    sa.Column('q5', sa.Text(), nullable=True),
    sa.Column('photo_base64', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meets')
    # ### end Alembic commands ###
